### ISSUE TITLE
Combining labels with a custom resource prevents logs from being recorded

### ISSUE THREAD

**Issue by priestjim** [googleapis/nodejs-logging-winston#85] opened 2018-05-24 19:38 UTC
#### Environment details

  - OS: node:8.11.2 docker image
  - Node.js version: 8.11.2
  - npm version: 5.6.0
  - `@google-cloud/logging-winston` version: 0.9.0

#### Steps to reproduce

- Initialize a Winston logger with LoggingWinston
- Define a custom resource with the proper project labels
- Define custom default labels to be emitted with the specified resource
- Log a line with labels
- The event will be rejected by Stackdriver (or never emitted)

```javascript
const { LoggingWinston } = require('@google-cloud/logging-winston');
sdLoggingOptions = { 
  logName: 'custom_logname', 
  resource: { 
    type: 'gae_app',
    labels: {
      project_id: 'my-project-id',
      module_id: 'default',
      version_id: 1
    }
  },
  labels: {
    main_app: true
  }
};
let logger = new winston.Logger({
  level: 'info',
  transports: [new LoggingWinston(sdLoggingOptions)]
});
logger.info('This will be recorded properly');
logger.info('This will NOT be recorded properly', {custom_metadata: 'yes', labels: {log_line: 'sample'}});
```

The first event will be logged properly with the extra labels attached to the log entry but the second event will not be logged AT ALL.

**Comment by DominicKramer** [comment] 2018-05-25 17:34
Thank you for opening this issue.  I do not know off hand why the second event is not being logged, and we will need to look into it.  We will keep this thread updated as we explore the issue.  Thanks.

**Comment by FernandoPinto** [comment] 2018-11-07 11:11
Any updated on this issue ?
I am having the same problem. 
Every time I try to log with custom metadata the logs don't get logged, although if I put only a single property it works (in my case I wanted to log a json object tough).

**Comment by DominicKramer** [comment] 2019-01-31 22:14
I am unable to reproduce this bug.  That is, in the following Typescript example (using Winston 3), both of the `logger.info` calls are reported to both the console and Stackdriver with the correct metadata.

Are you still seeing this bug with your code?

```ts
import * as winston from 'winston';
import * as lw from '@google-cloud/logging-winston';

const loggingWinston = new lw.LoggingWinston({
  projectId: 'my-project',
  serviceContext: {
    service: 'my-service',
    version: '1'
  },
  logName: 'custom_logname',
  resource: {
    type: 'gce_instance',
    labels: {
      project_id: 'my-project-id',
      module_id: 'default',
      version_id: '1'
    }
  },
  labels: {
    main_app: 'true'
  }
});

const logger = winston.createLogger({
  level: 'info',
  transports: [
    new winston.transports.Console(),
    loggingWinston
  ]
});

const timestamp = Date.now();
logger.info(`Test message at ${timestamp}`);
logger.info(`Test message with metadata at ${timestamp}`, {
  custom_metadata: 'yes',
  labels: {
    log_line: 'sample'
  }
});
```

**Comment by DominicKramer** [comment] 2019-02-04 21:43
I am closing this for now since I cannot reproduce this bug.  If anyone is still experiencing this bug, we can reopen the bug at that time.

**Closed by DominicKramer** 2019-02-04 21:43 UTC
Labels: :rotating_light:, priority: p2, type: bug
