### ISSUE TITLE
Using this library in cloud functions results in incorrect resource `region` label

### ISSUE THREAD

**Issue by sarveshraj** [googleapis/nodejs-logging-winston#749] opened 2022-10-17 08:27 UTC
I have a cloud function running in `us-central1` region. Logs created by GCP have the correct (`us-central1`) region label set but any application logs using this library have the region label set to `us1`.

GCP log:
<img width="843" alt="Screenshot 2022-10-17 at 1 49 33 PM" src="https://user-images.githubusercontent.com/35839390/196126945-abdce2ee-b515-4d14-a30a-2b2db6a75f9f.png">

Application log:
<img width="843" alt="Screenshot 2022-10-17 at 1 54 09 PM" src="https://user-images.githubusercontent.com/35839390/196127044-1ab44eab-7bc3-40e3-aa66-ee5deeeac10c.png">

--- 
Node.js: 16
This library: 5.1.0

**Comment by meredithslota** [comment] 2023-04-28 19:38
Hi @sarveshraj — that's really curious. I can't find anything in the library where we're customizing the region. We're just passing through any `labels` found into the metadata entry, as far as I can tell. And `us1` is a Google App Engine zone, similar to `us-central`, which is translated to `us-central1` elsewhere in GCP, as per https://cloud.google.com/appengine/docs/standard/locations Are you by chance using GAE?

**Comment by meredithslota** [comment] 2023-04-28 19:48
I do see, however, some parsing of zones/regions in the `nodejs-logging` library here (https://github.com/googleapis/nodejs-logging/blob/main/src/utils/metadata.ts). Are you using GAE or Cloud Run?

**Comment by sarveshraj** [comment] 2023-04-28 20:28
> I do see, however, some parsing of zones/regions in the `nodejs-logging` library here ([googleapis/nodejs-logging@`main`/src/utils/metadata.ts](https://github.com/googleapis/nodejs-logging/blob/main/src/utils/metadata.ts?rgh-link-date=2023-04-28T19%3A48%3A19Z)). Are you using GAE or Cloud Run?

This is in Google Cloud functions.

**Comment by meredithslota** [comment] 2023-04-28 21:54
Ok, I think I found a clue — it does look like we're translating from `zone` to `region` in the `nodejs-logging` library (which is used by _this_ library) here: https://github.com/googleapis/nodejs-logging/blob/main/src/utils/metadata.ts#L34 because GCF dynamically allocates zones (and possibly we couldn't get the region data directly previously?). However, if `region` is already defined by an environment variable, we can use that instead: https://github.com/googleapis/nodejs-logging/blob/main/src/utils/metadata.ts#L49 It seems like this is "works as intended" based on the comment in the code but also it's possible we need to update how we do this and reconsider the intent here, ha. I'm going to convert this to a feature request to see if we need to update how we figure out regions (more) appropriately.

**Comment by meredithslota** [comment] 2023-04-28 21:56
For future reference: https://github.com/googleapis/nodejs-logging/issues/1026

**Comment by cindy-peng** [comment] 2023-10-19 22:18
Hi @sarveshraj , I tried to reproduce the issue on a newly created cloud function located in `us-central1`, however the region label was populated correctly for me even from the logging library. I used the same winston package mentioned in this issue: "@google-cloud/logging-winston" :"5.1.0".

Here is what I found in the logging from GCP vs logging library:

GCP log:
<img width="1437" alt="image" src="https://github.com/googleapis/nodejs-logging-winston/assets/148148319/914da461-25e4-4676-b5bd-7e8cc16fd360">

Logging library:
<img width="1211" alt="image" src="https://github.com/googleapis/nodejs-logging-winston/assets/148148319/55a69db6-9f3b-45b0-858d-ecd78f065d1d">

Please help check if you have any environment variables including GOOGLE_CLOUD_REGION or FUNCTION_REGION set for your function, since that will take precedence over the parsed region value as mentioned by meredithslota earlier: https://github.com/googleapis/nodejs-logging/blob/main/src/utils/metadata.ts#L63

I am closing this issue for now since this can't be repro from our side. Feel free to re-open it and provide more details if you are still running into this issue.

**Closed by cindy-peng** 2023-10-19 22:18 UTC
Labels: priority: p2, type: feature request, api: logging
