### ISSUE TITLE
Missing HTTP log level

### ISSUE THREAD

**Issue by VictorLNoCapInc** [googleapis/nodejs-logging-winston#692] opened 2022-04-13 22:18 UTC
**Is your feature request related to a problem? Please describe.**
I am using http log level (default log level from winston) to display result of API calls.
But it makes @google-cloud/loggin-winston crash because http log level is unknown for the package.
Here is the error:
`Error: Unknown log level: http at LoggingCommon.log (/app/node_modules/@google-cloud/logging-winston/build/src/common.js:107:19) at LoggingWinston.log
`

 **Describe the solution you'd like**
Just add http log level support or at least don't throw an error.

**Comment by minherz** [comment] 2022-04-14 03:20
Looking at winston documentation about log levels i do not find "http" level. The existing code indeed throws exception:
(https://github.com/googleapis/nodejs-logging-winston/blob/a76167f123552007e8dba4005ae77ec384eb3494/src/common.ts#L48-L55)
https://github.com/googleapis/nodejs-logging-winston/blob/a76167f123552007e8dba4005ae77ec384eb3494/src/common.ts#L170-L172

The exception is thrown if the provided log level is not one of the names in the winston [Logging Levels](https://github.com/winstonjs/winston/tree/2.x#logging-levels). To have the problem more visual for us, can you please provide a simple application source code that demonstrates the problem?

**Comment by losalex** [comment] 2022-11-30 04:54
I think that this one is related to the same issue: [757](https://github.com/googleapis/nodejs-logging-winston/issues/757)

**Comment by losalex** [comment] 2022-12-22 20:32
Closing as duplicate of [757](https://github.com/googleapis/nodejs-logging-winston/issues/757)

**Closed by losalex** 2022-12-22 20:32 UTC
Labels: priority: p3, type: feature request, api: logging
