### ISSUE TITLE
Cloud Function Nodejs 10 intermittent Error: Could not load the default credentials.

### ISSUE THREAD

**Issue by 27Bslash6** [googleapis/nodejs-logging-winston#443] opened 2020-01-22 01:07 UTC
#### Environment details

  - OS: Google Cloud Functions
  - Node.js version: 10 beta
  - `@google-cloud/logging-winston` version: 3.0.5

#### Steps to reproduce

  1. Deploy cloud function with this library and sample code:
```javascript
const winston = require('winston');

// Imports the Google Cloud client library for Winston
const {LoggingWinston} = require('@google-cloud/logging-winston');

const loggingWinston = new LoggingWinston();

// Create a Winston logger that streams to Stackdriver Logging
// Logs will be written to: "projects/YOUR_PROJECT_ID/logs/winston_log"
const logger = winston.createLogger({
  level: 'info',
  transports: [
    new winston.transports.Console(),
    // Add Stackdriver Logging
    loggingWinston,
  ],
});

// Writes some log entries
logger.error('warp nacelles offline');
logger.info('shields at 99%');

exports.main = async function (req, res) {
  res.send('OK');
  logger.info('test');
  logger.info('test2');
}
```

Code appears to work consistently in NodeJS 8, but on Node 10 I experience intermittent `Error: Could not load the default credentials.` failures:

![image](https://user-images.githubusercontent.com/2221076/72854997-2f415700-3d0a-11ea-8f4d-1367ffee3fb9.png)

Possibly related: https://github.com/googleapis/google-auth-library-nodejs/issues/798

I also attempted to explicitly wait for logger `finish` events, and only send / end execution but this seems to make matters worse:

```javascript
exports.main = async function (req, res) {
  logger.on('finish', () => {
	res.send('OK');
  });
  logger.info('test');
  logger.info('test2');
  logger.end();
}
```

![image](https://user-images.githubusercontent.com/2221076/72856767-a6c5b500-3d0f-11ea-8009-9044fca4eb15.png)

**Comment by bcoe** [comment] 2020-01-22 01:10
:wave: I'm closing this as it's a duplicate of https://github.com/googleapis/google-auth-library-nodejs/issues/798, I'm sorry for how frustrating this is, we continue to dig into this internally.

I will keep the thread in auth library updated if any additional information is available :+1:

**Closed by bcoe** 2020-01-22 01:10 UTC

**Comment by bcoe** [comment] 2020-01-22 01:11
@27Bslash6 it's worth mentioning that if you explicitly provide service account credentials, see:

https://cloud.google.com/docs/authentication/getting-started

You should be able to avoid this behavior.

**Comment by 27Bslash6** [comment] 2020-01-22 01:13
Okay sure, I wasn't sure if it was directly related or if there was a way I could employ the available logging functions more correctly.

Thanks.
