### ISSUE TITLE
Logs not shown for Cloud Function nodejs10 runtime

### ISSUE THREAD

**Issue by MatthieuLemoine** [googleapis/nodejs-logging-winston#333] opened 2019-06-05 09:08 UTC
#### Environment details

  - OS: Cloud Function
  - Node.js version: 10.15.x
  - npm version:
  - `@google-cloud/logging-winston` version:0.11.1

#### Steps to reproduce

  1. Create a custom logger using logging-winston as transport
  2. Deploy the cloud function on nodejs10 runtime
  3. Logs are not shown in Stackdriver Log viewer

While trying to migrate from Cloud function nodejs8 to nodejs10 runtime, I found out that logs are not shown in Stackdriver Log viewer. If I change the runtime back to nodejs8, it's working as intended.

Let me know if I should create an issue in Cloud Function's issue tracker on https://issuetracker.google.com

**Comment by ofrobots** [comment] 2019-06-05 16:47
Related: https://github.com/googleapis/nodejs-logging-bunyan/issues/291, with the root cause in https://github.com/googleapis/nodejs-logging-bunyan/issues/291#issuecomment-484607243.

We're working with the Cloud Functions team to get this resolved /cc @steren.

**Comment by ofrobots** [comment] 2019-06-11 16:38
@steren this is blocked on the Cloud Functions side. I don't have permissions to open an issue against Cloud Functions on https://issuetracker.google.com. Can open a bug on that side?

**Comment by steren** [comment] 2019-06-11 19:49
We have an internal tracking bug (131353611)

**Comment by ofrobots** [comment] 2019-06-11 20:28
@steren is there a public version of the bug so that @MatthieuLemoine can follow along on progress?

**Comment by steren** [comment] 2019-06-11 20:58
This GitHub issue? I do not see the advantage of creating one more issue.

**Comment by tanishiking** [comment] 2019-08-26 15:31
Hi there, this problem seems fixed in https://github.com/googleapis/google-auth-library-nodejs/pull/748 which is available as of google-auth-library v4.2.6, right?
I confirmed that it is working correctly in my following environment.

Google Cloud Function with nodejs10
@google-cloud/logging-winston version: 1.1.1

Thank you so much for working on this issue :)

**Comment by soldair** [comment] 2019-08-30 22:18
@MatthieuLemoine some details i added here might help you work around the issue for now. 
https://github.com/googleapis/nodejs-logging-bunyan/issues/291#issuecomment-526758642

**Comment by bcoe** [comment] 2019-09-05 14:42
@MatthieuLemoine @soldair I've gone ahead and closed this issue, because it sounds like we addressed it in a patch to `google-auth-library-nodejs`; please feel free to reopen if you're continuing to bump into issues.

**Closed** 2019-09-05 14:41 UTC
Labels: priority: p2, status: blocked, type: bug
