### ISSUE TITLE
Logging-winston on AppEngine

### ISSUE THREAD

**Issue by remydavid** [googleapis/nodejs-logging-winston#175] opened 2018-09-25 16:31 UTC
- OS: macOS
  - Node.js version: 8.12.0
  - npm version: 6.4.1
  - `@google-cloud/logging-winston` version: 0.10.0

```js
const winston = require('winston');
const express = require('express');

(async () => {
const Logger = winston.Logger;
const Console = winston.transports.Console;

// Imports the Google Cloud client library for Winston
const LoggingWinston = require('@google-cloud/logging-winston').LoggingWinston;

// Creates a Winston Stackdriver Logging client
const loggingWinston = new LoggingWinston({
  projectId: 'myprojectid',
  keyFilename: 'gcp_key.json',
  prefix: 'myservice',
  serviceContext: {
    service: 'myservice', 
    version: 'dev'
  }
});

// Create a Winston logger that streams to Stackdriver Logging
const logger = winston.createLogger({
  level: 'info', // log at 'info' and above
  transports: [
    // Log to the console
    new Console(),
    // And log to Stackdriver Logging
    loggingWinston
  ]
});

const app = express();

app.get('/', (req, res) => {
  logger.info('This is an info message');
  logger.error('This is an error message');
});

// Start the server
const PORT = process.env.PORT || 8080;
server = app.listen(PORT, async () => {
    logger.info(`App listening on port ${PORT}`);
});

})();
```
 
package.json :
```  "dependencies": {
    "@google-cloud/logging-winston": "^0.10.0",
    "express": "^4.16.3",
    "winston": "^3.1.0"
  }
```

This is a very basic test of nodejs-logging-winston on AppEngine standard nodejs8 env with latest winston/logging-winston versions.

Here are a few problems/though out of the box : 
- No matter what I do I get the following warning :
```
undefined is a legacy winston transport. Consider upgrading:
Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```
- Logs logged with Logger.info or Logger.error shows as any in Stackdriver, although I provided a service context (the sample from the repo do not, but I think it should, otherwise it gives false impression that Logger.error is working as expected in the sample, which is not)
- Why should we provide a service name and version into the service context ? this should not be hardcoded in the Logger creation but dynamically taken from the running AppEngine configuration.

**Comment by soldair** [comment] 2018-09-25 17:16
thanks for the report! I'll take a look

**Comment by soldair** [comment] 2018-09-25 19:31
There is a bug associating the serviceContext with errors. it looks like the logging winston3 wrapper is doing something extra it shouldn't and ill work on that patch.

But I'm unable to reproduce your error with the code you provided. =/
```
undefined is a legacy winston transport. Consider upgrading:
Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```
little notes. you should be able to delete the project id and key config.  The client libraries read GOOGLE_APPLICATION_CREDENTIALS from the environment.
```
  projectId: 'myprojectid',
  keyFilename: 'gcp_key.json',
```

what do you have in your app.yaml? i tested with only "runtime: nodejs8" 

notes:
In general winston 3 expects more like structured log messages. logs that are objects. The examples need to be updated based on whats best practice for winston 3 now that we support it =)

`logger.error` always makes an error level error in logging but it wont cause an entry to be inserted into error reporting unless the object logged has both a "message" and a "stack" property like a Error object in js.

```js
logger.error(new Error('this error is very serious'))
```

winston 3's default `Console` logger expects you to log objects now. So if you'ed like something that looks nice in both console, stackdriver logging, and error reporting the same way. 
You can use a log message like 
```js
logger.error({message:error.message,stack:error.stack,... anything else you like})
```

re service context.
i think this is more for you to set information we can't know. but it might make sense to make it read the information from the environment by default. ill ask some other folks what folks generally consider its purpose to be =)

i'll comment on this issue when passing service context for errors its working with winston3

**Comment by shaunc869** [comment] 2018-12-04 22:36
I have this same error with the same versions:

const logger = winston.createLogger({
    level: 'info',
    transports: [
        new winston.transports.Console({
            format: winston.format.combine(winston.format.colorize(), winston.format.simple()),
        }),
        loggingWinston,
    ],
});

**Comment by soldair** [comment] 2018-12-07 18:41
hey @shaunc869 the service cobntext issue is fixed. 
could you clarify what issue you're seeing?
and @remydavid are you still running into an issue or did the patch work for you?

**Comment by DominicKramer** [comment] 2019-02-01 19:31
@soldair Do you think this issue should be closed?

**Comment by ofrobots** [comment] 2019-02-13 02:06
The serviceContext issue has been resolved. Without more info, there is nothing more to do here. I'm going to close this out.

If there is any more info available and the bug is still present, please add a comment and we will reopen.

**Closed by ofrobots** 2019-02-13 02:06 UTC
Labels: needs more info, status: investigating, type: question
