### ISSUE TITLE
Suddenly "Attempt to write logs with no transport..." and no logs at all

### ISSUE THREAD

**Issue by seriousManual** [googleapis/nodejs-logging-winston#258] opened 2019-02-07 11:36 UTC
#### Environment details

  - OS: Linux dev-devops-1 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 GNU/Linu
 - Environment: Google App Engine 
  - Node.js version: 10.14.2
  - `@google-cloud/logging-winston` version: 0.10.2
 - winston version: 3.1.0

#### Steps to reproduce
Unfortunately I dont have the means of reproducing the issue.

Today from one moment to the other winston started to write "[winston] Attempt to write logs with no transports" messages to stderr, at the same time the actual logs in stackdriver ("winston_log") did not show up anymore.

After a while these messages also stopped appearing, still no stackdriver logs in "winston_log".

_This issue was "fixed" by redeploying the app on App Engine._

Can you give some advice on how to prevent the logs from vanishing completely?

**Comment by DominicKramer** [comment] 2019-02-07 18:20
Thanks for opening this issue.  I do not know offhand what would be causing this.  I will try to reproduce this, to get some insight.

**Comment by DominicKramer** [comment] 2019-02-07 18:21
Also, did you only see this problem on AppEngine, or did it also occur when running locally?  Thanks.

**Comment by seriousManual** [comment] 2019-02-08 07:56
Hi,
locally I'm not working with the logging-winston transport (only logging to the Console).
This seems only to happen when the app ran for a longer period of time.

When I checked the logs today the same thing happened again, on two different apps. Interestingly on both apps the logs dropped out at around 7:35 AM (CET).

**Comment by seriousManual** [comment] 2019-02-08 08:10
This maybe is related:
A few days ago these errors started to appear in Error Reporting. They appear very seldom are are definetly somehow related to logging:

![image](https://user-images.githubusercontent.com/1330022/52466088-5cd8d300-2b81-11e9-83d6-c41a0bdd081b.png)

**Comment by ofrobots** [comment] 2019-02-12 01:36
This seems to be a duplicate of https://github.com/googleapis/nodejs-logging/issues/381. I'll close this out over here. Please leave a comment if this is incorrect.

**Closed by ofrobots** 2019-02-12 01:36 UTC
Labels: priority: p1, type: bug

**Comment by seriousManual** [comment] 2019-02-12 08:01
Thanks, looks good.
