### ISSUE TITLE
Library still throws if we try to log a large object

### ISSUE THREAD

**Issue by tsilvap** [googleapis/nodejs-logging-winston#428] opened 2019-12-19 18:37 UTC
#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: v10.18.0
  - npm version: 6.13.4
  - `@google-cloud/logging-winston` version: 3.0.2

#### Steps to reproduce

  1. Suppose `veryLargeString` is a variable containing a string with about 100,000 characters.
  2. Try to run the "Quickstart" code snippet in the README (having appropriately set the authentication environment variables), but try to run the following line: `logger.info(veryLargeString);`. The code will run without issues, and log the string to Stackdriver Logging.
  3. Now try to run the following line: `logger.info('foo', { veryLargeString });`. The code throws with the following error trace:
```
(node:20708) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Log entry with size 1.00M exceeds maximum size of 256.0K
    at Object.callErrorFromStatus (/tmp/logging.D0fP/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/tmp/logging.D0fP/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (/tmp/logging.D0fP/node_modules/@grpc/grpc-js/build/src/call-stream.js:98:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:20708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am I to believe that this is not intended behavior, as #404 should fix this?

**Comment by soldair** [comment] 2019-12-20 21:20
it seems like the size constraint doesn't work on objects.

**Comment by bcoe** [comment] 2019-12-31 00:42
@soldair the logic that checks max entry size serializes the payload before checking its size:

https://github.com/googleapis/nodejs-logging/blob/e22b6959f81155989f7507c9450b5a93506bc83a/src/log.ts#L887

Mind taking a second look at the logic? I know I tested both logging objects and strings.

@tsilvap does this happen if you log a large string?

**Comment by tsilvap** [comment] 2019-12-31 02:46
@bcoe It does not happen if you just log a string (even if it is very large, more than 256KB). It seems that this behavior only happens with objects.

**Comment by soldair** [comment] 2020-01-03 21:08
@tsilvap could you edit the compiled version of this function in your node_modules and console log  enough in this function to find out where it might be falling down with your exact reproduction?

https://github.com/googleapis/nodejs-logging/blob/e22b6959f81155989f7507c9450b5a93506bc83a/src/log.ts#L885

**Comment by nickhsine** [comment] 2020-01-04 01:56
I encounter the same problem.
And I guess 
`const payloadSize = JSON.stringify(entry).length;` 
cannot count the exactly total length of entry if entry is an instance of `Error`.

For instance,
```
import axios from 'axios'
import logger from './logger' 
import util from 'util'

axios.get('http://localhost:8080/record-not-found')
.catch((err) => {
  // axios returns an Error instance,
  // however, in `err`,
  // there are many properties,
  // such as `request`, `config`, `response` ... etc.
  
  console.log(JSON.stringify(err).length)
  // print 1018
  
  console.log(util.inspect(err).length)
  // print 8018
})
```

**Comment by nickhsine** [comment] 2020-01-04 06:38
I encounter the same problem.
After my test, you can see the following demo code.
Even if `truncateEntries` executed, the entry still could be larger than `this.maxEntrySize`

```
// demo code
import axios from 'axios'
import loggerFactory from './logger'   // loggin-winston
import util from 'util'

const logger = loggerFactory.getLogger()

axios.get('http://localhost:8080/v1/record-not-found')
  .catch((err) => {
    logger.error(err)
  })
```
`maxEntrySize` is `250000`,
the `payloadSize` before truncate is `300059`,
and the `payloadSize` after truncate is `298757`.
For `winston`, 
only truncate
`jsonPayload.fields.metadata.structValue.fields.stack.stringValue` and 
`jsonPayload.fields.message.stringValue`
seems not enough ?

**Comment by tsilvap** [comment] 2020-01-06 11:33
@soldair I think @nickshine is correct. It appears that the function only truncates the following fields:
```
const fieldsToTruncate = [
    // Winston:
    'jsonPayload.fields.metadata.structValue.fields.stack.stringValue',
    // Bunyan:
    'jsonPayload.fields.msg.stringValue',
    'jsonPayload.fields.err.structValue.fields.stack.stringValue',
    'jsonPayload.fields.err.structValue.fields.message.stringValue',
    // All:
    'jsonPayload.fields.message.stringValue',
];
```


I think that is not enough to truncate every possible object. For example, in my code, the very large string will end up in the field `jsonPayload.fields.metadata.structValue.fields.veryLargeString.stringValue`, and that field is not truncated by the function.

Indeed, if we try to log another object, say `{ a: { b: 'a'.repeat(100000) } }`, now we'll have a large string in the field `jsonPayload.fields.metadata.structValue.fields.a.structValue.fields.b.stringValue`, which also won't be truncated, and so on.

So, it appears that the current logic for `truncateEntries` can't truncate objects very well. I'm not sure what would be a way to fix it that could handle arbitrary objects.

**Comment by soldair** [comment] 2020-01-06 19:39
Could you propose an acceptable algorithm that might work the way we'ed need on objects? I'm not sure if there is a generic enough computationally viable solution to this.

like data could be preserved based on how close it is to the top of the json object. doing a shallow first count of bytes. Then arbitrary keys at a certain depth would be truncated after bytes are exhausted. It's hard to say this is what every user will expect/

**Comment by soldair** [comment] 2020-01-21 16:40
I'm going to close this for now because we don't have a viable way to solve this.
The cost of dynamically truncating arbitrarily nested strings inside of custom objects is too much and too complex to not be surprising.

it would be nice if this never threw. it's not a good user experience. instead we should perhaps log the error message or a broken json object truncated like a string.

we should open another issue with our decision here.

**Closed by soldair** 2020-01-21 16:40 UTC
Labels: priority: p2, type: bug

**Comment by fiendfiend** [comment] 2020-02-20 14:33
Forgive my directness, but what's the point of closing an issue on the basis of not yet having a viable solution to it, only to have to open a new issue later, isn't the entire purpose of logging the issue to track the identification and resolution?

Leaving the issue open to retain visibility of the problem seems like a reasonable approach in such a situation, no?

**Comment by rhodgkins** [comment] 2020-03-24 15:55
I agree with @fiendfiend - the fact that the logger stops working as soon as you get a `Error: 3 INVALID_ARGUMENT: Log entry with size 355.6K exceeds maximum size of 256.0K` error isn't great either as it means all long after that is just dropped...

**Comment by rhodgkins** [comment] 2020-03-25 12:40
Found a fix for this - use a version of Winston that has [1679c49](https://github.com/winstonjs/winston/commit/1679c496fb720cad495b78e987dcd8b921de9cc9) (i.e. `yarn add winstonjs/winston#73ae01f951600306242e00dd0d2b0a85b6d9d254`) and then add the following error event hander to your `LoggingWinston` transport:

```js
const { createLogger } = require('winston')
const { LoggingWinston } = require('@google-cloud/logging-winston')

const transporter = new LoggingWinston()
// This prevents the unhandled promise rejection
transporter.on('error', err => {
   console.error('Transport error', err)
})

const logger = createWinstonLogger({ transports: [transporter] })
// This is only here if you want to use structured logs for the error
transporter.on('error', err => {
   logger.error('Transport error', err)
})
```

**Comment by sshevlyagin** [comment] 2022-08-02 03:29
I ran into this with `5.1.2`, the following workaround helped at least detect that something is going wrong.
``` 
new LoggingWinston(
defaultCallback: err => {
      if (err) {
        console.log('Logging error occurred: ' + err);
      }
    }
)
```

**Comment by benitogonzalezh** [comment] 2022-10-12 02:08
In my case, to solve the issue I created a wrapper for the LoggingWinston with a custom truncate logic before send the message to the logger.

```javascript
const TransportStream = require('winston-transport');
const { LoggingWinston } = require('@google-cloud/logging-winston')

class wrapperGoogleLogsTransport extends TransportStream {
  constructor(opts) {
    super(opts)
    this.googleLogsTransport = new LoggingWinston(opts)
  }

  log(info, callback) {
   // here you can write your custom logic, like truncate or maybe chunk info in parts and send by part
    const sizeInfo = JSON.stringify(info).length
    if (sizeInfo > 256000) {
      info = JSON.stringify(metadata).substring(0, 256000)
    }
    this.googleLogsTransport.log(info, callback)
  }
}

export default wrapperGoogleLogsTransport
```

**Comment by losalex** [comment] 2022-12-13 01:38
A while ago, I did a fix in base `nodejs-logging` library to support more fields for truncation - here is a PR [1177](https://github.com/googleapis/nodejs-logging/pull/1177). Thats said, I never exposed this logic in `nodejs-logging-winston` - please let me know if this is something you would like me to do.
In addition, recently I changed the logic to include [partialSuccess](https://github.com/googleapis/nodejs-logging/pull/1359) to be `true` by default - this at least make sure that only oversized entries will be dropped from request (if of course the size of the request itself does not goes beyond limit as specified in [log-limits](https://cloud.google.com/logging/quotas#log-limits)) - in this case while the error still would be returned, in response it will indicate which entries were dropped.
Also, I believe we should implement log splitting as mentioned in [LogSplit](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSplit) - this is a feature we can work on if there will be enough demand

**Comment by sshevlyagin** [comment] 2022-12-13 15:28
I'd use that @losalex !

**Comment by moriaor1** [comment] 2023-06-01 20:56
We encounter the same issue on our Cloud Run instances, and fixed it by adding the following fields to LoggingWinston transport options. [docs](https://cloud.google.com/nodejs/docs/reference/logging-winston/latest#alternative-way-to-ingest-logs-in-google-cloud-managed-environments)

```typescript
import { LoggingWinston } from '@google-cloud/logging-winston';


const transport = new LoggingWinston({
  useMessageField: false,
  redirectToStdout: true,
});
``` 

This way the error is not throwing and the log object appears as a truncated string.  


To maintain the log info as json we implemented @benitogonzalezh's solution (thank you!) with few modifications.

```typescript
import { LoggingWinston } from '@google-cloud/logging-winston';
import {
  isArray,
  isObject,
  isString,
  truncate,
} from 'lodash';

export function truncateObjectDeep(obj: any, length: number): any {
  if (isString(obj) && obj.length > length) {
    return truncate(obj, { length })};
  }
  if (isArray(obj)) {
    return obj.map(i => truncateObjectDeep(i, length));
  }
  if (isObject(obj)) {
    Object.keys(obj).forEach(key => {
      (obj as any)[key] = truncateObjectDeep((obj as any)[key], length);
    });
    return obj;
  }

  return obj;
}



class GoogleLogsTransport extends LoggingWinston {
  log(info: any, callback: (err: Error | null, apiResponse?: {}) => void) {
    const sizeInfo = JSON.stringify(info).length;
    if (sizeInfo > 250000) {
      info = truncateObjectDeep(info, 5000); // the max length for string values
      info.truncated = true;
    }
    super.log(info, callback);
  }
}


const transport = new GoogleLogsTransport({
    useMessageField: false,
    redirectToStdout: true,
  });


``` 

We assume that most large size logs will have few fields that are significantly larger. This will not work if our log is a very large object but all values are small in size.
