### ISSUE TITLE
Errors not logged to Stackdriver Error Reporting

### ISSUE THREAD

**Issue by jamesholcomb** [googleapis/nodejs-logging-winston#32] opened 2018-01-19 17:56 UTC
#### Environment details

  - OS: macOS
  - Node.js version: 8.9
  - npm version: 5.5.1
  - @google-cloud/logging-winston version: 0.7.0

#### Steps to reproduce
- startup node app, NODE_ENV=undefined or some other non-production value
- log an error that includes a stack trace
- error shows up in Stackdriver logs correctly
- error does not appear in Stackdriver Error Reporting

According to the doc, logged errors will appear in Stackdriver Error Reporting.

I have enabled a linked billing account and the service account I use has full permissions.

**Comment by DominicKramer** [comment] 2018-01-19 22:15
@jamesholcomb Thank you for bringing this to our attention.  We will look into it and will let you know what we find.

**Comment by jamesholcomb** [comment] 2018-01-19 23:50
Thanks.  Is it within the scope of this repo to utilize @google-cloud/error-reporting within the Winston transport to provide direct integration with Stackdriver error reporting?  There seem to be more options available in that lib.

**Comment by DominicKramer** [comment] 2018-01-20 00:59
The `@google-cloud/error-reporting` library does provide direct access to the Error Reporting API.  However, to minimize the numbers of dependencies of this library, I think your issue can be addressed without including `@google-cloud/error-reporting` as a dependency of this library.

That way, you will not need a direct or transitive dependency on `@google-cloud/error-reporting` unless you need its additional functionality.

**Comment by dinvlad** [comment] 2018-08-13 05:59
This is still an issue in the current version of the library - however, it says both in the [code](https://github.com/googleapis/nodejs-logging-winston/blob/23fc5dae7fa2968e3300e060c78ec7e67d730fae/src/index.ts#L137-L148) and in the [docs](https://cloud.google.com/error-reporting/docs/setup/nodejs#cloud_functions) that the errors are picked up automatically only if the log entry contains stack trace. Is that the intended behavior, or is it planned to be fixed? Ideally, we'd like to just log an error message, not necessarily with trace. Thanks!

**Comment by dinvlad** [comment] 2018-08-13 22:09
Has there been any progress towards resolving this issue?

**Comment by dinvlad** [comment] 2018-08-13 23:52
@jamesholcomb @DominicKramer I think there are currently 2 issues that prevent this from working properly:

1) This plugin's documentation should more clearly state that `serviceContext.service` must be defined when instantiating `LoggingWinston` object. This is documented behavior for [Stackdriver Error Reporting](https://cloud.google.com/error-reporting/docs/formatting-error-messages#json_representation), but not clearly explained here.

2) I believe there's a bug in the code https://github.com/googleapis/nodejs-logging-winston/blob/23fc5dae7fa2968e3300e060c78ec7e67d730fae/src/index.ts#L149
that currently requires **both** an error message **and** an error stack to be present in log options, even though only **one** of those is required, as explained in the documentation link from (2). Either one is fine, as long as it includes the error stack. Otherwise, we end up with the error message printed **twice** in the log - once as itself and once through the stack.

To address (2), we just need to change the above line to
```ts
     if (metadata || metadata.stack) { 
```
Let me know if you'd like a PR (this is a very simple change though).

**Comment by dinvlad** [comment] 2018-08-14 03:06
@jamesholcomb @DominicKramer Sorry for re-posting multiple times - I believe the first issue is that `serviceContext.service` must be defined when instantiating `LoggingWinston` object, and this may be non-obvious, though Error Reporting [docs](https://cloud.google.com/error-reporting/docs/formatting-error-messages#json_representation) do explain it.

Another nitpicky thing is that this part of the code https://github.com/googleapis/nodejs-logging-winston/blob/23fc5dae7fa2968e3300e060c78ec7e67d730fae/src/index.ts#L149-L152
expects the error to be logged in the format
```ts
logger.error("New error", { stack: err.stack })
```
otherwise it doesn't set `serviceContext` for the logged message, even if we include the stack in the message ourselves.

Note that the "final" logged message in this case will be `"New error Error: " + err.message`, because `err.message` is normally included as `"Error: " + err.message` at the beginning of `err.stack`.

Personally, I'd prefer to be able to log it using this shorthand instead:
```ts
logger.error(err.stack)
```
because `err.stack` already includes the error message _and_ the stack, and thus would be correctly parsed by Error Reporting. Instead, currently we have to do this to achieve the same result:
```ts
logger.error('', { stack: err.stack })
```

**Comment by DominicKramer** [comment] 2018-08-14 22:54
Thank you @dinvlad for looking into this issue.  Yes, it looks like there are two issues for getting errors to be reported to the Error Reporting console.

First, the error must be logged using the 'error' log level or higher, and is documented correctly so doesn't need to be addressed.

Second, the `serviceContext.service` property needs to be set.  This is a bug in this library, where the library should use a default value if the service is not specified.

I still need to investigate whether logging the error using `logger.error(err.stack)` is possible, but that will be addressed separately from the issue in this thread.

**Closed** 2018-08-27 18:32 UTC
Labels: :rotating_light:, priority: p2, type: bug

**Comment by aaaguirrep** [comment] 2019-06-23 15:49
Hi, any news about the issue? At present I have configured nodejs-logging-winston for Google Cloud Run service and the errors don't appears in stackdriver error console. I have setup the serviceContext but it didnt work.

**Comment by DominicKramer** [comment] 2019-06-24 15:29
@aaaguirrep The original issue in this thread should be fixed with PR #148.  I suspect the new issue you are now seeing is related to PR #333.  As such, I've opened a new issue (#354) to track errors not appearing for Google Cloud Run.

**Comment by boredland** [comment] 2019-12-02 14:48
How should this currently work?
```
const loggingWinston = new LoggingWinston({
serviceContext: {
    service: 'my-service', // required to report logged errors
                        // to the Google Cloud Error Reporting
                        // console
    version: 'my-version'
}
});
```
neither created a new service `my-service` in the error console, nor did my `logger.error()` end up anywhere there...

**Comment by germanp173** [comment] 2020-03-20 23:43
@boredland you need to specify the `serviceContext` as shown in your example and you need to pass a stack trace in your error call as @dinvlad mentioned.

The trick I found, however, is that specifying a `stack` manually with some random string as shown below did not work for me:
```
logger.error("", { stack: "some stack trace" })
```
Instead, I got it to work by passing an actual error exception like so:
```
logger.error("", new Error("some error here"))
```

**Comment by DominicKramer** [comment] 2020-03-24 16:18
Yes, a requirement of the Error Reporting API is that the error message must have a real stack trace.  Using `logger.error("", new Error("some error here"))` or `logger.error(new Error("some error here"))` is needed.
