### ISSUE TITLE
Object without format placeholder will not shows on StackDriver Log Viewer

### ISSUE THREAD

**Issue by neeon-li** [googleapis/nodejs-logging-winston#34] opened 2018-01-22 06:56 UTC
#### Environment details

  - OS: macOS 10.13.2
  - Node.js version: v8.9.3
  - npm version: 5.6.0
  - @google-cloud/logging-winston version: v0.7.0

#### Steps to reproduce

  1. Just use the following codes:
```
const winston = require('winston');
const LoggingWinston = require('@google-cloud/logging-winston');

const Console = winston.transports.Console;
const loggingWinston = new LoggingWinston({
  projectId: 'nova-gcp-development-testing',
  keyFilename: path.join(
    __dirname,
    'stackdriver@nova-gcp-development-testing.iam.gserviceaccount.com.json'
  ),
});

const sklogger = new winston.Logger({
  level: 'debug',
  transports: [new Console(), loggingWinston],
});

const str1 = 'String 1';
sklogger.debug('string with format: %s', str1);
sklogger.debug('string without format:', str1);

const num1 = 100;
sklogger.debug('number with format: %d', num1);
sklogger.debug('number without format:', num1);

const float1 = 100;
sklogger.debug('float with format: %d', float1);
sklogger.debug('float without format:', float1);

const obj1 = { key1: '1', key2: 2 };
sklogger.debug('object with format: %j', obj1);
sklogger.debug('object without format:', obj1);
```
  2. Execute the codes
  3. Go to GCP console and inspect StackDriver Log Viewer

It shows normally in Console:
![screen shot 2018-01-22 at 2 43 49 pm](https://user-images.githubusercontent.com/25143608/35208517-e57b4b3c-ff83-11e7-9b10-356511dcaa16.png)

But not excepted in StackDriver Log Viewer:
![screen shot 2018-01-22 at 2 44 05 pm](https://user-images.githubusercontent.com/25143608/35208520-e8d918e0-ff83-11e7-85b1-2eaf7bf631d8.png)

Is this normal ?
Also is it possible to change the option for LoggingWinston() without changing the source code to solve this problem ?

**Comment by DominicKramer** [comment] 2018-01-23 17:54
Thank you for letting us know about this.  I'm not sure offhand if this is normal.  We'll look into it and will let you know what we find.  Thanks.

**Comment by ofrobots** [comment] 2018-01-23 17:58
This looks like a bug to me.

**Comment by phantomnat** [comment] 2018-02-12 09:26
I think this is normal.
The object was on the metadata in jsonPayload that ok for me and I don't want it to show on message

![screen shot 2561-02-12 at 4 09 34 pm](https://user-images.githubusercontent.com/962802/36090080-7203beb6-1011-11e8-9e5d-863ea7603a3e.png)

**Comment by DominicKramer** [comment] 2018-02-22 21:23
So it looks like this issue can be closed.  However, @phantomnat I would think having `[Object]` or something similar listed in the message (with the object in the metadata) would be better than having nothing in the message.  However, before making that change, I would like to get your feedback if that change is necessary.  Thanks.

**Comment by neeon-li** [comment] 2018-02-23 01:10
@DominicKramer I agree with that at least having some message better than nothing.
I just want to output is as same as the Winston (which this package built for).
So that people don't need to learn / remember the Winston and logging-winston are output differently.

**Comment by phantomnat** [comment] 2018-02-23 11:11
@DominicKramer Yeah, I think so. It would be better to have something show on the output.

**Comment by jamesholcomb** [comment] 2018-04-11 14:17
Also seeing an issue logging messages that contain an array in the metadata, for example:

    logger.info("TEST", [{ foo: "bar" }])

does not render any metadata stackdriver output.

I would expect something like

    jsonPayload: { message: "TEST", metadata: { '0': { foo: 'bar'} } }

and more control over the `util.inspect` depth

**Comment by DominicKramer** [comment] 2018-11-11 18:19
To be in alignment with Winston 3 and to avoid having duplicate data in log messages, I think it would be best to not use the implementation in PR #159, and to close this issue as expected behavior.

**Closed by DominicKramer** 2018-11-11 18:19 UTC
Labels: :rotating_light:, priority: p2, type: bug
